In [1]:
import pandas as pd
import numpy as np

In [11]:
credits_df = pd.read_csv('/content/credits.csv', low_memory=False)
credits_df.head(10)

,cast,crew,id
0,"[{'cast_id': 14, 'character': 'Woody (voice)',...","[{'credit_id': '52fe4284c3a36847f8024f49', 'de...",862.0
1,"[{'cast_id': 1, 'character': 'Alan Parrish', '...","[{'credit_id': '52fe44bfc3a36847f80a7cd1', 'de...",8844.0
2,"[{'cast_id': 2, 'character': 'Max Goldman', 'c...","[{'credit_id': '52fe466a9251416c75077a89', 'de...",15602.0
3,"[{'cast_id': 1, 'character': ""Savannah 'Vannah...","[{'credit_id': '52fe44779251416c91011acb', 'de...",31357.0
4,"[{'cast_id': 1, 'character': 'George Banks', '...","[{'credit_id': '52fe44959251416c75039ed7', 'de...",11862.0
5,"[{'cast_id': 25, 'character': 'Lt. Vincent Han...","[{'credit_id': '52fe4292c3a36847f802916d', 'de...",949.0
6,"[{'cast_id': 1, 'character': 'Linus Larrabee',...","[{'credit_id': '52fe44959251416c75039da9', 'de...",11860.0
7,"[{'cast_id': 2, 'character': 'Tom Sawyer', 'cr...","[{'credit_id': '52fe46bdc3a36847f810f797', 'de...",45325.0
8,"[{'cast_id': 1, 'character': 'Darren Francis T...","[{'credit_id': '52fe44dbc3a36847f80ae0f1', 'de...",9091.0
9,"[{'cast_id': 1, 'character': 'James Bond', 'cr...","[{'credit_id': '52fe426ec3a36847f801e14b', 'de...",710.0

In [12]:
keywords_df = pd.read_csv('/content/keywords.csv', low_memory=False)
keywords_df.head(20)

       id                                           keywords
0     862  [{'id': 931, 'name': 'jealousy'}, {'id': 4290,...
1    8844  [{'id': 10090, 'name': 'board game'}, {'id': 1...
2   15602  [{'id': 1495, 'name': 'fishing'}, {'id': 12392...
3   31357  [{'id': 818, 'name': 'based on novel'}, {'id':...
4   11862  [{'id': 1009, 'name': 'baby'}, {'id': 1599, 'n...
5     949  [{'id': 642, 'name': 'robbery'}, {'id': 703, '...
6   11860  [{'id': 90, 'name': 'paris'}, {'id': 380, 'nam...
7   45325                                                 []
8    9091  [{'id': 949, 'name': 'terrorist'}, {'id': 1562...
9     710  [{'id': 701, 'name': 'cuba'}, {'id': 769, 'nam...
10   9087  [{'id': 833, 'name': 'white house'}, {'id': 84...
11  12110  [{'id': 3633, 'name': 'dracula'}, {'id': 11931...
12  21032  [{'id': 1994, 'name': 'wolf'}, {'id': 6411, 'n...
13  10858  [{'id': 840, 'name': 'usa president'}, {'id': ...
14   1408  [{'id': 911, 'name': 'exotic island'}, {'id': ...
15    524  [{'id': 383, 'name': 'poker'}, {'id': 726, 'na...
16   4584  [{'id': 420, 'name': 'bowling'}, {'id': 818, '...
17      5  [{'id': 612, 'name': 'hotel'}, {'id': 613, 'na...
18   9273  [{'id': 409, 'name': 'africa'}, {'id': 1551, '...
19  11517  [{'id': 380, 'name': 'brother brother relation...

In [ ]:
movies_df = pd.read_csv('/content/movies_metadata.csv', sep=',')
movies_df.head()

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,1995-10-30,373554033,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,1995-12-15,262797249,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,1995-12-22,0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0
3,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,1995-12-22,81452156,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,1995-02-10,76578911,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0

Warning: Total number of columns (24) exceeds max_columns (20) limiting to first (20) columns.

In [27]:
c = movies_df['vote_average'].mean()
c

5.605397799948836

In [17]:
m = movies_df['vote_count'].quantile(0.90)
m

156.0

In [21]:
maxi=np.max(movies_df['vote_average'])
mini=np.min(movies_df['vote_average'])

In [26]:
record = movies_df[movies_df['vote_average'] == maxi]
record.head()

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
186,False,NaN,0,"[{'id': 14, 'name': 'Fantasy'}, {'id': 35, 'na...",NaN,58372,tt0114241,en,Reckless,"On Christmas eve, a relentlessly cheerful woma...",...,1995-11-17,0,91.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The most twisted Christmas ever.,Reckless,False,10.0,1.0
394,False,NaN,0,"[{'id': 10749, 'name': 'Romance'}, {'id': 12, ...",NaN,278939,tt0113173,en,Girl in the Cadillac,A runaway teenage girl and a drifter rob a ban...,...,1995-10-24,0,89.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,On our first date... we robbed a bank,Girl in the Cadillac,False,10.0,1.0
706,False,NaN,0,"[{'id': 99, 'name': 'Documentary'}]",NaN,73183,tt0113270,en,"The Haunted World of Edward D. Wood, Jr.",The strange life and the wonderfully awful fil...,...,1996-05-01,0,112.0,[],Released,Can your MIND stand the SHOCKING TRUTH?,"The Haunted World of Edward D. Wood, Jr.",False,10.0,1.0
738,False,NaN,0,"[{'id': 99, 'name': 'Documentary'}]",NaN,255546,tt0109381,pt,Carmen Miranda: Bananas Is My Business,A biography of the Portuguese-Brazilian singer...,...,1995-04-13,0,91.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,NaN,Carmen Miranda: Bananas Is My Business,False,10.0,1.0
1634,False,NaN,0,"[{'id': 18, 'name': 'Drama'}]",NaN,64562,tt0119845,en,Other Voices Other Rooms,Truman Capote's semi-autobiographical first no...,...,1995-09-15,0,0.0,[],Released,NaN,Other Voices Other Rooms,False,10.0,1.0

In [29]:
def weighted_rating(x,m=m,c=c):
  v=x['vote_count']
  R=x['vote_average']
  return (v/(v+m)*R)+(m/(m+v)*c)

In [30]:
q_movies = movies_df.copy().loc[movies_df['vote_count'] >= m]

In [31]:
q_movies['Score']= q_movies.apply(weighted_rating,axis=1)

In [32]:
q_movies = q_movies.sort_values('Score', ascending=False)
q_movies[['title','vote_count', 'vote_average', 'Score']].head(15)

                                 title  vote_count  vote_average     Score
314           The Shawshank Redemption      8358.0           8.5  8.446963
10309      Dilwale Dulhania Le Jayenge       661.0           9.1  8.432732
834                      The Godfather      6024.0           8.5  8.426932
12481                  The Dark Knight     12269.0           8.3  8.266168
2843                        Fight Club      9678.0           8.3  8.257255
292                       Pulp Fiction      8670.0           8.3  8.252373
522                   Schindler's List      4436.0           8.3  8.208459
23673                         Whiplash      4376.0           8.3  8.207247
5481                     Spirited Away      3968.0           8.3  8.198070
2211                 Life Is Beautiful      3643.0           8.3  8.189350
1178            The Godfather: Part II      3418.0           8.3  8.182384
1152   One Flew Over the Cuckoo's Nest      3001.0           8.3  8.166849
351                       Forrest Gump      8147.0           8.2  8.151252
1176                            Psycho      2405.0           8.3  8.135862
1154           The Empire Strikes Back      5998.0           8.2  8.134228

In [35]:
q_movies.shape

(4695, 25)

In [33]:
q_movies['overview'].head()

314      Framed in the 1940s for the double murder of h...
10309    Raj is a rich, carefree, happy-go-lucky second...
834      Spanning the years 1945 to 1955, a chronicle o...
12481    Batman raises the stakes in his war on crime. ...
2843     A ticking-time-bomb insomniac and a slippery s...
Name: overview, dtype: object

In [34]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer(stop_words='english')
q_movies['overview'] = q_movies['overview'].fillna('')
tfidf_matrix = tfidf.fit_transform(q_movies['overview'])
tfidf_matrix.shape

(4695, 19890)

In [41]:
from sklearn.metrics.pairwise import linear_kernel
consine_sim = linear_kernel(tfidf_matrix, tfidf_matrix)

In [42]:
consine_sim.shape

(4695, 4695)

In [38]:
indices = pd.Series(q_movies.index, index = q_movies['title']).drop_duplicates()

In [43]:
def recomendar(title, consine_sim = consine_sim):
  idx = indices[title]
  sim_scores = list(enumerate(consine_sim[idx]))
  sim_scores= sorted(sim_scores, key=lambda x: x[1], reverse = True)
  sim_scores = sim_scores[1:11]
  movies_indices = [i[0] for i in sim_scores]
  return q_movies['title'].iloc[movies_indices]

In [44]:
recomendar('Forrest Gump')

4113                                         Just Visiting
11955                                             Stardust
10597    The Chronicles of Narnia: The Lion, the Witch ...
359                                          The Lion King
4691                                              Joy Ride
9698                                  Howl's Moving Castle
6893                                           The Witches
5091                                     Y Tu Mamá También
9182                             Kirikou and the Sorceress
30122                                          The Cobbler
Name: title, dtype: object

In [49]:
columnas = movies_df.columns.tolist()
columnas

['adult',
 'belongs_to_collection',
 'budget',
 'genres',
 'homepage',
 'id',
 'imdb_id',
 'original_language',
 'original_title',
 'overview',
 'popularity',
 'poster_path',
 'production_companies',
 'production_countries',
 'release_date',
 'revenue',
 'runtime',
 'spoken_languages',
 'status',
 'tagline',
 'title',
 'video',
 'vote_average',
 'vote_count']

In [50]:
columnas = credits_df.columns.tolist()
columnas

['cast', 'crew', 'id']

In [51]:
columnas = keywords_df.columns.tolist()
columnas

['id', 'keywords']

In [52]:
print(movies_df.shape)
print(credits_df.shape)
print(keywords_df.shape)

(46917, 24)
(45662, 3)
(46419, 2)

In [53]:
join1=pd.merge(credits_df, keywords_df, on='id')

In [54]:
join1.head()

,cast,crew,id,keywords
0,"[{'cast_id': 14, 'character': 'Woody (voice)',...","[{'credit_id': '52fe4284c3a36847f8024f49', 'de...",862.0,"[{'id': 931, 'name': 'jealousy'}, {'id': 4290,..."
1,"[{'cast_id': 1, 'character': 'Alan Parrish', '...","[{'credit_id': '52fe44bfc3a36847f80a7cd1', 'de...",8844.0,"[{'id': 10090, 'name': 'board game'}, {'id': 1..."
2,"[{'cast_id': 2, 'character': 'Max Goldman', 'c...","[{'credit_id': '52fe466a9251416c75077a89', 'de...",15602.0,"[{'id': 1495, 'name': 'fishing'}, {'id': 12392..."
3,"[{'cast_id': 1, 'character': ""Savannah 'Vannah...","[{'credit_id': '52fe44779251416c91011acb', 'de...",31357.0,"[{'id': 818, 'name': 'based on novel'}, {'id':..."
4,"[{'cast_id': 1, 'character': 'George Banks', '...","[{'credit_id': '52fe44959251416c75039ed7', 'de...",11862.0,"[{'id': 1009, 'name': 'baby'}, {'id': 1599, 'n..."

In [55]:
join1.shape

(46681, 4)

In [61]:
def is_integer(n):
    try:
        float_n = float(n)
        int_n = int(float_n)
    except ValueError:
        return False
    else:
        return float_n == int_n


movies_df = movies_df[movies_df['id'].apply(is_integer)]

In [ ]:
non_int_ids = movies_df[~movies_df['id'].apply(is_integer)]
print(non_int_ids)

In [62]:
movies_df.shape

(46913, 24)

In [ ]:
#df3 = df3.drop_duplicates(subset=['Name'])

In [64]:
# Convertir la columna 'id' a float en ambos DataFrames
join1['id'] = join1['id'].astype(float)
movies_df['id'] = movies_df['id'].astype(float)

# Ahora puedes hacer la unión
join2 = pd.merge(join1, movies_df, on='id')

In [65]:
join2.shape

(48269, 27)

In [66]:
join2.head()

,cast,crew,id,keywords,adult,belongs_to_collection,budget,genres,homepage,imdb_id,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,"[{'cast_id': 14, 'character': 'Woody (voice)',...","[{'credit_id': '52fe4284c3a36847f8024f49', 'de...",862.0,"[{'id': 931, 'name': 'jealousy'}, {'id': 4290,...",False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,tt0114709,...,1995-10-30,373554033,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0
1,"[{'cast_id': 1, 'character': 'Alan Parrish', '...","[{'credit_id': '52fe44bfc3a36847f80a7cd1', 'de...",8844.0,"[{'id': 10090, 'name': 'board game'}, {'id': 1...",False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,tt0113497,...,1995-12-15,262797249,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,"[{'cast_id': 2, 'character': 'Max Goldman', 'c...","[{'credit_id': '52fe466a9251416c75077a89', 'de...",15602.0,"[{'id': 1495, 'name': 'fishing'}, {'id': 12392...",False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,tt0113228,...,1995-12-22,0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0
3,"[{'cast_id': 1, 'character': ""Savannah 'Vannah...","[{'credit_id': '52fe44779251416c91011acb', 'de...",31357.0,"[{'id': 818, 'name': 'based on novel'}, {'id':...",False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,tt0114885,...,1995-12-22,81452156,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0
4,"[{'cast_id': 1, 'character': 'George Banks', '...","[{'credit_id': '52fe44959251416c75039ed7', 'de...",11862.0,"[{'id': 1009, 'name': 'baby'}, {'id': 1599, 'n...",False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,tt0113041,...,1995-02-10,76578911,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0