In [1]:
import pandas as pd
import numpy as np

In [9]:
#Importar archivo csv, separador '|'
df = pd.read_csv('/content/tom.txt', sep='|')
#Hechar un vistaso a los primeros registros
df.tail(20)

                                         Alabama[edit]
546  Montgomery (West Virginia University Institute...
547           Morgantown (West Virginia University)[2]
548             Shepherdstown (Shepherd University)[2]
549          West Liberty (West Liberty University)[2]
550                                    Wisconsin[edit]
551                     Appleton (Lawrence University)
552    Eau Claire (University of Wisconsin–Eau Claire)
553      Green Bay (University of Wisconsin-Green Bay)
554  La Crosse (University of Wisconsin–La Crosse, ...
555       Madison (University of Wisconsin–Madison)[2]
556       Menomonie (University of Wisconsin–Stout)[2]
557  Milwaukee (Marquette University, University of...
558          Oshkosh (University of Wisconsin–Oshkosh)
559  Platteville (University of Wisconsin–Plattevil...
560  River Falls (University of Wisconsin–River Fal...
561  Stevens Point (University of Wisconsin–Stevens...
562                      Waukesha (Carroll University)
563  Whitewater (University of Wisconsin–Whitewater...
564                                      Wyoming[edit]
565                 Laramie (University of Wyoming)[5]

In [5]:
tom = []
with open('/content/tom.txt') as file:
  for line in file:
    if '[edit]' in line:
      state = line
    else:
      tom.append((state, line))

In [ ]:
tom[:50]

In [14]:
len(tom)

517

In [15]:
towns_df = pd.DataFrame(tom, columns=['State','RegionName'])

In [17]:
towns_df.head(10)

             State                                         RegionName
0  Alabama[edit]\n                    Auburn (Auburn University)[1]\n
1  Alabama[edit]\n           Florence (University of North Alabama)\n
2  Alabama[edit]\n  Jacksonville (Jacksonville State University)[2]\n
3  Alabama[edit]\n       Livingston (University of West Alabama)[2]\n
4  Alabama[edit]\n         Montevallo (University of Montevallo)[2]\n
5  Alabama[edit]\n                        Troy (Troy University)[2]\n
6  Alabama[edit]\n  Tuscaloosa (University of Alabama, Stillman Co...
7  Alabama[edit]\n                Tuskegee (Tuskegee University)[5]\n
8   Alaska[edit]\n    Fairbanks (University of Alaska Fairbanks)[2]\n
9  Arizona[edit]\n       Flagstaff (Northern Arizona University)[6]\n

In [21]:
  def get_citystate(item):
    if ' (' in item:
      return item[:item.find(' (')]
    elif '[' in item:
      return item[:item.find('[')]
    else: return item

In [23]:
towns_df = towns_df.applymap(get_citystate)

In [25]:
towns_df.head(15)

       State    RegionName
0    Alabama        Auburn
1    Alabama      Florence
2    Alabama  Jacksonville
3    Alabama    Livingston
4    Alabama    Montevallo
5    Alabama          Troy
6    Alabama    Tuscaloosa
7    Alabama      Tuskegee
8     Alaska     Fairbanks
9    Arizona     Flagstaff
10   Arizona         Tempe
11   Arizona        Tucson
12  Arkansas   Arkadelphia
13  Arkansas        Conway
14  Arkansas  Fayetteville

In [33]:
f=get_citystate(tom[:1])

In [34]:
print(f)

[('Alabama[edit]\n', 'Auburn (Auburn University)[1]\n')]

In [42]:
#Importar archivo csv, separador '|'
df1 = pd.read_csv('/content/olympics.csv', header=1)
#Hechar un vistaso a los primeros registros
df1.tail(20)

,Unnamed: 0,? Summer,01 !,02 !,03 !,Total,? Winter,01 !.1,02 !.1,03 !.1,Total.1,? Games,01 !.2,02 !.2,03 !.2,Combined total
127,Togo (TOG),9,0,0,1,1,1,0,0,0,0,10,0,0,1,1
128,Tonga (TGA),8,0,1,0,1,1,0,0,0,0,9,0,1,0,1
129,Trinidad and Tobago (TRI) [TRI],16,2,5,11,18,3,0,0,0,0,19,2,5,11,18
130,Tunisia (TUN),13,3,3,4,10,0,0,0,0,0,13,3,3,4,10
131,Turkey (TUR),21,39,25,24,88,16,0,0,0,0,37,39,25,24,88
132,Uganda (UGA),14,2,3,2,7,0,0,0,0,0,14,2,3,2,7
133,Ukraine (UKR),5,33,27,55,115,6,2,1,4,7,11,35,28,59,122
134,United Arab Emirates (UAE),8,1,0,0,1,0,0,0,0,0,8,1,0,0,1
135,United States (USA) [P] [Q] [R] [Z],26,976,757,666,2399,22,96,102,84,282,48,1072,859,750,2681
136,Uruguay (URU),20,2,2,6,10,1,0,0,0,0,21,2,2,6,10
137,Uzbekistan (UZB),5,5,5,10,20,6,1,0,0,1,11,6,5,10,21
138,Venezuela (VEN),17,2,2,8,12,4,0,0,0,0,21,2,2,8,12
139,Vietnam (VIE),14,0,2,0,2,0,0,0,0,0,14,0,2,0,2
140,Virgin Islands (ISV),11,0,1,0,1,7,0,0,0,0,18,0,1,0,1
141,Yugoslavia (YUG) [YUG],16,26,29,28,83,14,0,3,1,4,30,26,32,29,87
142,Independent Olympic Participants (IOP) [IOP],1,0,1,2,3,0,0,0,0,0,1,0,1,2,3
143,Zambia (ZAM) [ZAM],12,0,1,1,2,0,0,0,0,0,12,0,1,1,2
144,Zimbabwe (ZIM) [ZIM],12,3,4,1,8,1,0,0,0,0,13,3,4,1,8
145,Mixed team (ZZX) [ZZX],3,8,5,4,17,0,0,0,0,0,3,8,5,4,17
146,Totals,27,4809,4775,5130,14714,22,959,958,948,2865,49,5768,5733,6078,17579

In [47]:
new_names ={
  'Unnamed: 0':'Country',
  '? Summer':'Summer Olympics',
  '01 !':'Gold',
  '02 !':'Silver',
  '03 !':'Bronce',
  '? Winter':'Winter Olympics',
  '01 !.1':'Gold.1',
  '02 !.1':'Silver.1',
  '03 !.1':'Bronce.1',
  '? Games':'# Games',
  '01 !.2':'Gold.2',
  '02 !.2':'Silver.2',
  '03 !.2':'Bronce.3'}

In [50]:
df1.rename(columns=new_names,inplace=True)
df1.head(20)

,Country,Summer Olympics,Gold,Silver,Bronce,Total,Winter Olympics,Gold.1,Silver.1,Bronce.1,Total.1,# Games,Gold.2,Silver.2,Bronce.3,Combined total
0,Afghanistan (AFG),13,0,0,2,2,0,0,0,0,0,13,0,0,2,2
1,Algeria (ALG),12,5,2,8,15,3,0,0,0,0,15,5,2,8,15
2,Argentina (ARG),23,18,24,28,70,18,0,0,0,0,41,18,24,28,70
3,Armenia (ARM),5,1,2,9,12,6,0,0,0,0,11,1,2,9,12
4,Australasia (ANZ) [ANZ],2,3,4,5,12,0,0,0,0,0,2,3,4,5,12
5,Australia (AUS) [AUS] [Z],25,139,152,177,468,18,5,3,4,12,43,144,155,181,480
6,Austria (AUT),26,18,33,35,86,22,59,78,81,218,48,77,111,116,304
7,Azerbaijan (AZE),5,6,5,15,26,5,0,0,0,0,10,6,5,15,26
8,Bahamas (BAH),15,5,2,5,12,0,0,0,0,0,15,5,2,5,12
9,Bahrain (BRN),8,0,0,1,1,0,0,0,0,0,8,0,0,1,1
10,Barbados (BAR) [BAR],11,0,0,1,1,0,0,0,0,0,11,0,0,1,1
11,Belarus (BLR),5,12,24,39,75,6,6,4,5,15,11,18,28,44,90
12,Belgium (BEL),25,37,52,53,142,20,1,1,3,5,45,38,53,56,147
13,Bermuda (BER),17,0,0,1,1,7,0,0,0,0,24,0,0,1,1
14,Bohemia (BOH) [BOH] [Z],3,0,1,3,4,0,0,0,0,0,3,0,1,3,4
15,Botswana (BOT),9,0,1,0,1,0,0,0,0,0,9,0,1,0,1
16,Brazil (BRA),21,23,30,55,108,7,0,0,0,0,28,23,30,55,108
17,British West Indies (BWI) [BWI],1,0,0,2,2,0,0,0,0,0,1,0,0,2,2
18,Bulgaria (BUL) [H],19,51,85,78,214,19,1,2,3,6,38,52,87,81,220
19,Burundi (BDI),5,1,0,0,1,0,0,0,0,0,5,1,0,0,1

In [125]:
#Importar archivo csv, separador '|'
df3 = pd.read_excel('/content/raw-customer-churn-data.xlsx')
#Hechar un vistaso a los primeros registros
df3.tail(20)

/usr/local/lib/python3.10/dist-packages/openpyxl/worksheet/_reader.py:329: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)

                 Name  Gender   Age Payment Method  Churn  LastTransaction
979      Hope Bridges  female  42.0    credit card  churn               91
980   Mercedes Austin    male  80.0         cheque  loyal              109
981       Kyle Cooper    male  43.0    credit card  loyal               49
982     Jessie Jordan    male  23.0    credit card  loyal               59
983  Rosemary Maxwell  female  29.0    credit card  loyal               57
984       Troy Parker  female  44.0    credit card  churn               89
985       Roger Pratt    male  37.0           cash  loyal               45
986   Alton Underwood    male  26.0    credit card  loyal               58
987      William Pena    male  21.0    credit card  loyal               66
988  Suzanne Mcdonald  female  80.0         cheque  churn               56
989        Patti Bush    male  50.0           cash  loyal              105
990    Ernestine Ross  female  28.0    credit card  loyal               23
991       Ivan Massey    male  82.0           cash  loyal               24
992  Shannon Mccarthy    male  64.0    credit card    NaN               43
993        Diana Mann    male  19.0    credit card  loyal               92
994      Whitney Lowe  female  29.0    credit card  loyal               33
995    Kelvin Sanchez    male  84.0    credit card  loyal              124
996     Jodi Buchanan    male  20.0    credit card    NaN               60
997   Billy Rodriquez    male  19.0    credit card  loyal               49
998      Marcella Fox  female  24.0    credit card  loyal               25

In [126]:
#Eliminar espacios al comienzo y al final
df3 = df3.applymap(lambda x: x.strip() if isinstance(x, str) else x)
df3.head(20)

                Name  Gender   Age Payment Method  Churn  LastTransaction
0    Nicolas Garrett    male  64.0    credit card  loyal               98
1        Isaac Reyes    male  35.0         cheque  churn              118
2     Jaime Sullivan  female  25.0    credit card  loyal              107
3   Geraldine Miller  female  39.0    credit card    NaN              177
4     Curtis Frazier       m  39.0    credit card  loyal               90
5     Jeannie Palmer  female  28.0         cheque  churn              189
6     Phyllis Romero  female  21.0    credit card  loyal              102
7     Maxine Edwards  female   NaN         cheque  loyal              111
8        Marty Cohen     NaN  32.0         cheque  churn               50
9     Lionel Mendoza    male  48.0    credit card  loyal              141
10    Maureen Norman  female  70.0    credit card  churn              153
11     Santiago Cruz    male  36.0    credit card  loyal               46
12     Santiago Cruz    male  36.0    credit card  loyal               46
13      Nelson Davis    male  22.0    credit card  loyal               51
14   Josephine Owens  female  53.0           cash    NaN              183
15   Clarence Vaughn    male  27.0           cash  loyal              137
16       Jon Griffin    male  22.0           cash  loyal              147
17       Nettie Neal  female  49.0    credit card  churn              158
18    Belinda Reeves  female  24.0           cash  churn              162
19     Taylor Murphy    male  45.0    credit card  loyal               55

In [77]:
#Remplazamos los campos vacios por 'No register'
#df3['Churn'] = df3['Churn'].fillna('No register')

In [116]:
#Las personas que no registraon genero las cambiamos por 'Otro', debido a que cada vez mas gente tiene problemas con eso
#df3['Gender'] = df3['Gender'].fillna('Otro')

In [130]:
#Las personas que no registraron su genero no se tienen en cuenta
#df3['Gender'] =df3['Gender'].dropna()
df3 = df3.dropna(subset=['Gender'])

df3.head(10)

                Name  Gender   Age Payment Method  Churn  LastTransaction
0    Nicolas Garrett    male  64.0    credit card  loyal               98
1        Isaac Reyes    male  35.0         cheque  churn              118
2     Jaime Sullivan  female  25.0    credit card  loyal              107
3   Geraldine Miller  female  39.0    credit card    NaN              177
4     Curtis Frazier       m  39.0    credit card  loyal               90
5     Jeannie Palmer  female  28.0         cheque  churn              189
6     Phyllis Romero  female  21.0    credit card  loyal              102
7     Maxine Edwards  female   NaN         cheque  loyal              111
9     Lionel Mendoza    male  48.0    credit card  loyal              141
10    Maureen Norman  female  70.0    credit card  churn              153

In [117]:
#Hay personas que m quieren decir male y f quieren decir female
df3['Gender'] = df3['Gender'].replace('m', 'male')
df3['Gender'] = df3['Gender'].replace('f', 'female')

In [118]:
#Para conservar la mayor cantidad de informacion, ponemos la edad del registro anterior a la persona que no puso edad
df3['Age']=df3['Age'].fillna(method='bfill')

In [ ]:
df3.head(20)

In [120]:
df3.shape

(999, 6)

In [121]:
df3 = df3.drop_duplicates(subset=['Name'])

In [122]:
df3.shape

(998, 6)

In [123]:
df3['Name'].is_unique

True

In [124]:
#Guardamos todos los cambios en un nuevo archivo plano
df3.to_excel("customercleanData.xlsx", index=False)